version: '3.8'

services:
  db-test:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
    ports:
      - "5432:5432"

  app-test:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: test
      JAVA_OPTS: "-Dspring.profiles.active=test"
    depends_on:
      - db-test
    ports:
      - "8080:8080"
    command: [ "java", "-jar", "app.jar" ]